// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvmdZXkNJr_4uS-CWftDQ5t2ecw5jqZU',
    appId: '1:1065746435600:web:10efa985e13b2de9614495',
    messagingSenderId: '1065746435600',
    projectId: 'feeding-game-2ad54',
    authDomain: 'feeding-game-2ad54.firebaseapp.com',
    storageBucket: 'feeding-game-2ad54.appspot.com',
    measurementId: 'G-ZLSYJWBLW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoZCQdhzNoVU-a6ya6CMreRchrBmmgAcE',
    appId: '1:1065746435600:android:904169a337c9f14a614495',
    messagingSenderId: '1065746435600',
    projectId: 'feeding-game-2ad54',
    storageBucket: 'feeding-game-2ad54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgsVwjw6ZcKiYYlCSboSEzB23F14ogn7Y',
    appId: '1:1065746435600:ios:bf0059aba13fadfe614495',
    messagingSenderId: '1065746435600',
    projectId: 'feeding-game-2ad54',
    storageBucket: 'feeding-game-2ad54.appspot.com',
    iosBundleId: 'com.example.flutterAlememoProject',
  );
}
